library(effsize)

cat("\n\n###### GenProg ########\n")
mydata = read.csv("gp_rq5_incommondefects.csv", header=TRUE)
cat("#defects eval:", length(unique(mydata$defect)), "\n")
cat("#patches eval:", nrow(mydata), "\n")
x <- subset(mydata, mydata$provenance=="developer")
y <- subset(mydata, mydata$provenance=="EvoSuite")
cat("##### GenProg Mann-Whitney U Test #########\n")
wilcox.test(x$passpercentage, y$passpercentage)
cat("##### GenProg Cliffs'Delta ########\n")
cliff.delta(x$passpercentage,y$passpercentage, conf.level=.95)
cat("##############################\n")

pdf("gp_provenance_boxplot.pdf")
par(mar=c(2.5,4.5,1,1))
boxplot(mydata$passpercentage ~ mydata$provenance, yaxs="i", yaxt="n", cex.lab=2, cex.axis=2, ylab="patch quality (%)", ylim=c(0,105)) 
means <- tapply(mydata$passpercent,mydata$provenance,mean)
points(means,col="red",pch=18)
axis(cex.axis=2,side=2,at=seq(0,105, by=5))
dev.off()

cat("\n\n###### Par ########\n")
mydata = read.csv("par_rq5_incommondefects.csv", header=TRUE)
cat("#defects eval:", length(unique(mydata$defect)), "\n")
cat("#patches eval:", nrow(mydata), "\n")
x <- subset(mydata, mydata$provenance=="developer")
y <- subset(mydata, mydata$provenance=="EvoSuite")
cat("##### PAR Mann-Whitney U Test #########\n")
wilcox.test(x$passpercentage, y$passpercentage)
cat("##### PAR Cliffs'Delta ########\n")
cliff.delta(x$passpercentage,y$passpercentage, conf.level=.95)
cat("##############################\n")

pdf("par_provenance_boxplot.pdf")
par(mar=c(2.5,4.5,1,1))
boxplot(mydata$passpercentage ~ mydata$provenance, yaxs="i", yaxt="n", cex.lab=2, cex.axis=2, ylab="patch quality (%)", ylim=c(0,105)) 
means <- tapply(mydata$passpercent,mydata$provenance,mean)
points(means,col="red",pch=18)
axis(cex.axis=2,side=2,at=seq(0,105, by=5))
dev.off()

cat("\n\n###### TRPAutoRepair ########\n")
mydata = read.csv("trp_rq5_incommondefects.csv", header=TRUE)
cat("#defects eval:", length(unique(mydata$defect)), "\n")
cat("#patches eval:", nrow(mydata), "\n")
x <- subset(mydata, mydata$provenance=="developer")
y <- subset(mydata, mydata$provenance=="EvoSuite")
cat("##### TRP Mann-Whitney U Test #########\n")
wilcox.test(x$passpercentage, y$passpercentage)
cat("##### TRP Cliff's Delta ########\n")
cliff.delta(x$passpercentage,y$passpercentage, conf.level=.95)
cat("##############################\n")

pdf("trp_provenance_boxplot.pdf")
par(mar=c(2.5,4.5,1,1))
boxplot(mydata$passpercentage ~ mydata$provenance, yaxs="i", yaxt="n", cex.lab=2, cex.axis=2, ylab="patch quality (%)", ylim=c(0,105)) 
means <- tapply(mydata$passpercent,mydata$provenance,mean)
points(means,col="red",pch=18)
axis(cex.axis=2,side=2,at=seq(0,105, by=5))
dev.off()
