library(ggplot2)
library(ggpubr)
library(plyr)
library(dplyr)
library(scales)
theme_set(theme_pubr())

gp <- read.csv("gp_rq1_overall.csv")
par <- read.csv("par_rq1_overall.csv")
trp <- read.csv("trp_rq1_overall.csv")

############# comment following block to consider all defects patched
eval_defects <- read.csv(file = "../evaluation-defects.txt")
gp_rq1_all <- read.csv(file="gp_rq1_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
trp_rq1_all <- read.csv(file="trp_rq1_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
par_rq1_all <- read.csv(file="par_rq1_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
evaldefectsgp <- intersect(gp_rq1_all$defect, eval_defects$defect)
evaldefectstrp <- intersect(trp_rq1_all$defect, eval_defects$defect)
evaldefectspar <- intersect(par_rq1_all$defect, eval_defects$defect)
gp <- subset(gp_rq1_all, gp_rq1_all$defect%in%evaldefectsgp == TRUE)
trp <- subset(trp_rq1_all, trp_rq1_all$defect%in%evaldefectstrp == TRUE)
par <- subset(par_rq1_all, par_rq1_all$defect%in%evaldefectspar == TRUE)
def<- read.csv("defective_rq1_overall.csv")
################

commondefectsgp <- intersect(gp$defect, def$defect) 
commondefectspar <- intersect(par$defect, def$defect) 
commondefectstrp <- intersect(trp$defect, def$defect) 

def_gp <- subset(def, def$defect%in%commondefectsgp == TRUE)
def_par <- subset(def, def$defect%in%commondefectspar == TRUE)
def_trp <- subset(def, def$defect%in%commondefectstrp == TRUE)

cat("GenProg\n")
def_gp_quality <- aggregate(def_gp$passpercentage, def_gp[2], FUN=max)
gp_quality <- aggregate(gp$passpercentage, gp[2], FUN=max)
gp_improvement <- gp_quality$x - def_gp_quality$x
cat("%defects with improvement > 0:", length(which(gp_improvement>0.0))*100/length(gp_improvement),"\n")
cat("%defects with improvement = 0:", length(which(gp_improvement==0.0))*100/length(gp_improvement),"\n")
cat("%defects with improvement < 0:", length(which(gp_improvement<0.0))*100/length(gp_improvement),"\n")

cat("#patches with improvement < 0:", length(which(gp_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(gp_improvement==0.0)), "\n")
cat("total #patches:", length(gp_improvement), "\n")

cat("min quality improvement:", min(gp_improvement), "\n")
cat("mean quality improvement:", mean(gp_improvement), "\n")
cat("median quality improvement:", median(gp_improvement), "\n")
cat("max quality improvement:", max(gp_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_gp$defect)), "\n")
cat(length(gp_improvement))


#pdf("provenance_evosuite_failingtestsdistribution.pdf")
#par(mgp=c(4.5,1,0))
#par(mar=c(6,6,2,4.5))
#barplot(evosuite_tests, las = 2, names.arg = data$defect, col="Black", xlab="defect", main="EvoSuite", ylab="failing test count", ylim=c(0,51), xlim=c(0,37), cex.lab=2, cex.axis=2, cex.main=2, cex.sub=2, yaxt="n")
#axis(cex.axis=2,side=2,at=seq(0,45, by=3), labels=seq(0,45, by=3))
#dev.off()

pdf("gp_quality_improvement_subset.pdf")
dtf <- data.frame(x = gp_quality$defect,y = gp_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(stat = "identity", fill = "black") + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 10)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=15.5))
dev.off()

cat("PAR\n")
def_par_quality <- aggregate(def_par$passpercentage, def_par[2], FUN=max)
par_quality <- aggregate(par$passpercentage, par[2], FUN=max)
par_improvement <- par_quality$x - def_par_quality$x
cat("min quality improvement:", min(par_improvement), "\n")
cat("mean quality improvement:", mean(par_improvement), "\n")
cat("median quality improvement:", median(par_improvement), "\n")
cat("max quality improvement:", max(par_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_par$defect)), "\n")
cat("%defects with improvement > 0:", length(which(par_improvement>0.0))*100/length(par_improvement),"\n")
cat("%defects with improvement = 0:", length(which(par_improvement==0.0))*100/length(par_improvement),"\n")
cat("%defects with improvement < 0:", length(which(par_improvement<0.0))*100/length(par_improvement),"\n")
cat("#patches with improvement < 0:", length(which(par_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(par_improvement==0.0)), "\n")
cat("total #patches:", length(par_improvement), "\n")
pdf("par_quality_improvement_subset.pdf")
dtf <- data.frame(x = par_quality$defect,y = par_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(stat = "identity", fill = "black") + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 10)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=15.5))
#par(mar=c(4.5,5.1,2,2))
#par(mgp=c(4.5,1.5,0))
#par(mar=c(5.5,6.6,2,2))
#plot(par_improvement, lty=1, bty="n", type="h", lwd=9, xlab="defect", ylab="quality improvement", xaxt="n", yaxt="n", xlim=c(1,35), ylim=c(-40,40), cex.lab=3, cex.main=3, main="Par") + 
#abline(h=0, col="black", lwd=9)
#axis(cex.axis=3,side=1,at=seq(1,50, by=1))
#axis(cex.axis=3,side=1,at=seq(1,35, by=1))
#axis(cex.axis=3,side=2,at=seq(-40,40, by=5))
dev.off()

cat("TRP\n")
def_trp_quality <- aggregate(def_trp$passpercentage, def_trp[2], FUN=max)
trp_quality <- aggregate(trp$passpercentage, trp[2], FUN=max)
trp_improvement <- trp_quality$x - def_trp_quality$x
cat("min quality improvement:", min(trp_improvement), "\n")
cat("mean quality improvement:", mean(trp_improvement), "\n")
cat("median quality improvement:", median(trp_improvement), "\n")
cat("max quality improvement:", max(trp_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_trp$defect)), "\n")
cat("%defects with improvement > 0:", length(which(trp_improvement>0.0))*100/length(trp_improvement),"\n")
cat("%defects with improvement = 0:", length(which(trp_improvement==0.0))*100/length(trp_improvement),"\n")
cat("%defects with improvement < 0:", length(which(trp_improvement<0.0))*100/length(trp_improvement),"\n")

cat("#patches with improvement < 0:", length(which(trp_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(trp_improvement==0.0)), "\n")
cat("total #patches:", length(trp_improvement), "\n")
pdf("trp_quality_improvement_subset.pdf")
dtf <- data.frame(x = trp_quality$defect,y = trp_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(stat = "identity", fill = "black") + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 10)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=15.5))
#par(mar=c(4.5,5.1,2,2))
#par(mgp=c(4.5,1.5,0))
#par(mar=c(5.5,6.6,2,2))
#plot(trp_improvement, lty=1, bty="n", type="h", lwd=9, xlab="defect", ylab="quality improvement", xaxt="n", yaxt="n", xlim=c(1,35), ylim=c(-40,40), cex.lab=3, cex.main=3, main="TRPAutoRepair") + 
#abline(h=0, col="black", lwd=9)
#axis(cex.axis=3,side=1,at=seq(1,35, by=1))
#axis(cex.axis=3,side=1,at=seq(1,50, by=1))
#axis(cex.axis=3,side=2,at=seq(-40,40, by=5))
dev.off()
