#####################################
# PURPOSE: This is the driver script used to generate results for RQ1
# INPUT: path to directory containing patch quality assesment scores for RQ1 patches  (../../../results/RQ1/patch-quality-assessment/)
# OUTPUT: plots and results presented in paper
# CMD TO RUN: bash reproduce-rq1.sh ../../../results/RQ1/patch-quality-assessment/
# NOTE: this depends on consolidate.py and combineresults.py scripts to pre-process input data
#	and freq-distribution.R to generate the plots
#####################################

DIRPATH=$1

python consolidate.py $DIRPATH/gp_rq1_es3_quality.csv > gp_rq1_es3_consolidated.csv 
python consolidate.py $DIRPATH/gp_rq1_es6_quality.csv > gp_rq1_es6_consolidated.csv 
cat gp_rq1_es3_consolidated.csv > gp_rq1_es3_es6_consolidated.csv
cat gp_rq1_es6_consolidated.csv >> gp_rq1_es3_es6_consolidated.csv
sort gp_rq1_es3_es6_consolidated.csv > gp_rq1_es3_es6_consolidated_sorted.csv
python combineresults.py gp_rq1_es3_es6_consolidated_sorted.csv
mv results.csv gp_rq1_overall.csv
rm gp_rq1_es3_consolidated.csv
rm gp_rq1_es6_consolidated.csv
rm gp_rq1_es3_es6_consolidated.csv
rm gp_rq1_es3_es6_consolidated_sorted.csv

python consolidate.py $DIRPATH/trp_rq1_es3_quality.csv > trp_rq1_es3_consolidated.csv 
python consolidate.py $DIRPATH/trp_rq1_es6_quality.csv > trp_rq1_es6_consolidated.csv 
cat trp_rq1_es3_consolidated.csv > trp_rq1_es3_es6_consolidated.csv
cat trp_rq1_es6_consolidated.csv >> trp_rq1_es3_es6_consolidated.csv
sort trp_rq1_es3_es6_consolidated.csv > trp_rq1_es3_es6_consolidated_sorted.csv
python combineresults.py trp_rq1_es3_es6_consolidated_sorted.csv
mv results.csv trp_rq1_overall.csv
rm trp_rq1_es3_consolidated.csv
rm trp_rq1_es6_consolidated.csv
rm trp_rq1_es3_es6_consolidated.csv
rm trp_rq1_es3_es6_consolidated_sorted.csv

python consolidate.py $DIRPATH/par_rq1_es3_quality.csv > par_rq1_es3_consolidated.csv 
python consolidate.py $DIRPATH/par_rq1_es6_quality.csv > par_rq1_es6_consolidated.csv 
cat par_rq1_es3_consolidated.csv > par_rq1_es3_es6_consolidated.csv
cat par_rq1_es6_consolidated.csv >> par_rq1_es3_es6_consolidated.csv
sort par_rq1_es3_es6_consolidated.csv > par_rq1_es3_es6_consolidated_sorted.csv
python combineresults.py par_rq1_es3_es6_consolidated_sorted.csv
mv results.csv par_rq1_overall.csv
rm par_rq1_es3_consolidated.csv
rm par_rq1_es6_consolidated.csv
rm par_rq1_es3_es6_consolidated.csv
rm par_rq1_es3_es6_consolidated_sorted.csv

python consolidate-defective.py $DIRPATH/defective_rq1_es3_quality.csv > defective_rq1_es3_consolidated.csv 
python consolidate-defective.py $DIRPATH/defective_rq1_es6_quality.csv > defective_rq1_es6_consolidated.csv 
cat defective_rq1_es3_consolidated.csv > defective_rq1_es3_es6_consolidated.csv
cat defective_rq1_es6_consolidated.csv >> defective_rq1_es3_es6_consolidated.csv
sort defective_rq1_es3_es6_consolidated.csv > defective_rq1_es3_es6_consolidated_sorted.csv
python combineresults-defective.py defective_rq1_es3_es6_consolidated_sorted.csv
mv results.csv defective_rq1_overall.csv
rm defective_rq1_es3_consolidated.csv
rm defective_rq1_es6_consolidated.csv
rm defective_rq1_es3_es6_consolidated.csv
rm defective_rq1_es3_es6_consolidated_sorted.csv

python consolidate.py $DIRPATH/sim_rq1_es3_quality.csv > sim_rq1_es3_consolidated.csv 
python consolidate.py $DIRPATH/sim_rq1_es6_quality.csv > sim_rq1_es6_consolidated.csv 
cat sim_rq1_es3_consolidated.csv > sim_rq1_es3_es6_consolidated.csv
cat sim_rq1_es6_consolidated.csv >> sim_rq1_es3_es6_consolidated.csv
sort sim_rq1_es3_es6_consolidated.csv > sim_rq1_es3_es6_consolidated_sorted.csv
python combineresults.py sim_rq1_es3_es6_consolidated_sorted.csv
mv results.csv sim_rq1_overall.csv
rm sim_rq1_es3_consolidated.csv
rm sim_rq1_es6_consolidated.csv
rm sim_rq1_es3_es6_consolidated.csv
rm sim_rq1_es3_es6_consolidated_sorted.csv

echo "total #patches generated by GenProg:"
cat ../../../results/RQ1/patches/GenProg/genprog-results.txt | wc -l
echo "#unique patches generated by GenProg:"
ls ../../../results/RQ1/patches/GenProg/*.patch | wc -l

echo "total #patches generated by Par:"
cat ../../../results/RQ1/patches/Par/par-results.txt | wc -l
echo "#unique patches generated by Par:"
ls ../../../results/RQ1/patches/Par/*.patch | wc -l

echo "total #patches generated by TRPAutoRepair:"
cat ../../../results/RQ1/patches/TRPAutoRepair/trp-results.txt | wc -l
echo "#unique patches generated by TRPAutoRepair:"
ls ../../../results/RQ1/patches/TRPAutoRepair/*.patch | wc -l

echo "total #patches generated by SimFix: 76"
#ls ../../../results/RQ1/patches/SimFix/*.patch | wc -l
echo "#unique patches generated by SimFix:"
ls ../../../results/RQ1/patches/SimFix/*.patch | wc -l

Rscript freq-distribution.R
