library(dplyr)
library(ggplot2)
library(ggpubr)
theme_set(theme_pubr())

gp_rq6 <- read.csv(file="gp_rq6_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
trp_rq6 <- read.csv(file="trp_rq6_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
par_rq6 <- read.csv(file="par_rq6_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)

gp_dev <- subset(gp_rq6, gp_rq6$approach=="GenProg")
gp_nver <- subset(gp_rq6, gp_rq6$approach=="GenProg(n-version)")

trp_dev <- subset(trp_rq6, trp_rq6$approach=="TRPAutoRepair")
trp_nver <- subset(trp_rq6, trp_rq6$approach=="TRPAutoRepair(n-version)")

par_dev <- subset(par_rq6, par_rq6$approach=="Par")
par_nver <- subset(par_rq6, par_rq6$approach=="Par(n-version)")

cat("\n#############################################\n")
cat("GenProg\n")
cat("min:",min(gp_dev$passpercentage),"\n")
cat("mean:",mean(gp_dev$passpercentage),"\n")
cat("median:",median(gp_dev$passpercentage),"\n")
cat("max:",max(gp_dev$passpercentage),"\n")
cat("100%-quality:",length(which(gp_dev$passpercentage==100))/length(gp_dev$passpercentage),"\n")
cat("\n#############################################\n")
cat("GenProg N-version\n")
cat("min:",min(gp_nver$passpercentage),"\n")
cat("mean:",mean(gp_nver$passpercentage),"\n")
cat("median:",median(gp_nver$passpercentage),"\n")
cat("max:",max(gp_nver$passpercentage),"\n")
cat("100%-quality:",length(which(gp_nver$passpercentage==100))/length(gp_nver$passpercentage),"\n")
cat("\n#############################################\n")

cat("\n#############################################\n")
cat("\nPAR\n")
cat("min:",min(par_dev$passpercentage),"\n")
cat("mean:",mean(par_dev$passpercentage),"\n")
cat("median:",median(par_dev$passpercentage),"\n")
cat("max:",max(par_dev$passpercentage),"\n")
cat("100%-quality:",length(which(par_dev$passpercentage==100))/length(par_dev$passpercentage),"\n")
cat("\n#############################################\n")
cat("\nPAR N-version\n")
cat("min:",min(par_nver$passpercentage),"\n")
cat("mean:",mean(par_nver$passpercentage),"\n")
cat("median:",median(par_nver$passpercentage),"\n")
cat("max:",max(par_nver$passpercentage),"\n")
cat("100%-quality:",length(which(par_nver$passpercentage==100))/length(par_nver$passpercentage),"\n")

cat("\n#############################################\n")
cat("TRPAutoRepair\n")
cat("min:",min(trp_dev$passpercentage),"\n")
cat("mean:",mean(trp_dev$passpercentage),"\n")
cat("median:",median(trp_dev$passpercentage),"\n")
cat("max:",max(trp_dev$passpercentage),"\n")
cat("100%-quality:",length(which(trp_dev$passpercentage==100))/length(trp_dev$passpercentage),"\n")
cat("\n#############################################\n")
cat("TRPAutoRepair N-version\n")
cat("min:",min(trp_nver$passpercentage),"\n")
cat("mean:",mean(trp_nver$passpercentage),"\n")
cat("median:",median(trp_nver$passpercentage),"\n")
cat("max:",max(trp_nver$passpercentage),"\n")
cat("100%-quality:",length(which(trp_nver$passpercentage==100))/length(trp_nver$passpercentage),"\n")
cat("\n#############################################\n")

