library(effsize)

# boxplot for all patches

cat("\n########## GenProg\n")
mydata = read.csv("gp_rq6_overall.csv", header=TRUE)
x <- subset(mydata, mydata$approach=="GenProg")
y <- subset(mydata, mydata$approach=="GenProg(n-version)")
d <- unique(mydata$defect)
cat("#defects:", length(d), "\n")
cat("#n-version patches:", length(which(mydata$approach=="GenProg(n-version)")), "\n")
cat("#all patches:", length(which(mydata$approach=="GenProg")), "\n")
cat("\n##### GenProg Mann-Whitney U Test #########\n")
wilcox.test(x$passpercentage, y$passpercentage) 
cat("\n##### GenProg Cliffs'Delta ########\n")
cliff.delta(x$passpercentage,y$passpercentage, conf.level=.95)
cat("\n##############################\n")
pdf("gp_nversion_boxplot.pdf")
par(mar=c(2.5,4.5,1,1))
boxplot(mydata$passpercentage ~ mydata$approach, yaxs="i", yaxt="n", cex.main=1.62, cex.lab=1.62, cex.axis=1.62, ylab="patch quality (%)", ylim=c(70,101), xlab="", names = c("GenProg", "GenProg (n-version)")) 
means <- tapply(mydata$passpercent,mydata$approach,mean)
points(means,col="red",pch=18)
axis(cex.axis=1.62,side=2,at=seq(70,101, by=5))
dev.off()

cat("\n########## Par\n")
mydata = read.csv("par_rq6_overall.csv", header=TRUE)
x <- subset(mydata, mydata$approach=="Par")
y <- subset(mydata, mydata$approach=="Par(n-version)")
d <- unique(mydata$defect)
cat("#defects:", length(d), "\n")
cat("#n-version patches:", length(which(mydata$approach=="Par(n-version)")), "\n")
cat("#all patches:", length(which(mydata$approach=="Par")), "\n")
cat("\n##### Par Mann-Whitney U Test #########\n")
wilcox.test(x$passpercentage, y$passpercentage) 
cat("\n##### Par Cliffs'Delta ########\n")
cliff.delta(x$passpercentage,y$passpercentage, conf.level=.95)
cat("\n##############################\n")
pdf("par_nversion_boxplot.pdf")
par(mar=c(2.5,4.5,1,1))
boxplot(mydata$passpercentage ~ mydata$approach, yaxs="i", yaxt="n", cex.main=1.62, cex.lab=1.62, cex.axis=1.62, ylab="patch quality (%)", ylim=c(70,101), xlab="", names = c("Par", "Par (n-version)")) 
means <- tapply(mydata$passpercent,mydata$approach,mean)
points(means,col="red",pch=18)
axis(cex.axis=1.62,side=2,at=seq(70,101, by=5))
dev.off()

cat("\n########## TRPAutoRepair\n")
mydata = read.csv("trp_rq6_overall.csv", header=TRUE)
x <- subset(mydata, mydata$approach=="TRPAutoRepair")
y <- subset(mydata, mydata$approach=="TRPAutoRepair(n-version)")
d <- unique(mydata$defect)
cat("#defects:", length(d), "\n")
cat("#n-version patches:", length(which(mydata$approach=="TRPAutoRepair(n-version)")), "\n")
cat("#all patches:", length(which(mydata$approach=="TRPAutoRepair")), "\n")
cat("\n##### TRP Mann-Whitney U Test #########\n")
wilcox.test(x$passpercentage, y$passpercentage) 
cat("\n##### TRP Cliffs'Delta ########\n")
cliff.delta(x$passpercentage,y$passpercentage, conf.level=.95)
cat("\n##############################\n")
pdf("trp_nversion_boxplot.pdf")
par(mar=c(2.5,4.5,1,1))
boxplot(mydata$passpercentage ~ mydata$approach, yaxs="i", yaxt="n", cex.main=1.62, cex.lab=1.62, cex.axis=1.62, ylab="patch quality (%)", ylim=c(70,101),  xlab="", names = c("TRPAutoRepair", "TRPAutoRepair (n-version)")) 
means <- tapply(mydata$passpercent,mydata$approach,mean)
points(means,col="red",pch=18)
axis(cex.axis=1.62,side=2,at=seq(70,101, by=5))
dev.off()

