library(ggplot2)
library(ggpubr)
library(plyr)
library(dplyr)
library(scales)
theme_set(theme_pubr())

gp <- read.csv("gp_rq2_overall.csv")
par <- read.csv("par_rq2_overall.csv")
sim <- read.csv("sim_rq2_overall.csv")
trp <- read.csv("trp_rq2_overall.csv")

############# comment following block to consider all defects patched
eval_defects <- read.csv(file = "../evaluation-defects.txt")
gp_rq2_all <- read.csv(file="gp_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
trp_rq2_all <- read.csv(file="trp_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
par_rq2_all <- read.csv(file="par_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
sim_rq2_all <- read.csv(file="sim_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
evaldefectsgp <- intersect(gp_rq2_all$defect, eval_defects$defect)
evaldefectstrp <- intersect(trp_rq2_all$defect, eval_defects$defect)
evaldefectspar <- intersect(par_rq2_all$defect, eval_defects$defect)
evaldefectssim <- intersect(sim_rq2_all$defect, eval_defects$defect)
gp <- subset(gp_rq2_all, gp_rq2_all$defect%in%evaldefectsgp == TRUE)
trp <- subset(trp_rq2_all, trp_rq2_all$defect%in%evaldefectstrp == TRUE)
par <- subset(par_rq2_all, par_rq2_all$defect%in%evaldefectspar == TRUE)
sim <- subset(sim_rq2_all, sim_rq2_all$defect%in%evaldefectssim == TRUE)
def<- read.csv("defective_rq2_overall.csv")
################

commondefectsgp <- intersect(gp$defect, def$defect) 
commondefectspar <- intersect(par$defect, def$defect) 
commondefectstrp <- intersect(trp$defect, def$defect) 
commondefectssim <- intersect(sim$defect, def$defect) 

def_gp <- subset(def, def$defect%in%commondefectsgp == TRUE)
def_par <- subset(def, def$defect%in%commondefectspar == TRUE)
def_trp <- subset(def, def$defect%in%commondefectstrp == TRUE)
def_sim <- subset(def, def$defect%in%commondefectssim == TRUE)

cat("GenProg\n")
def_gp_quality <- aggregate(def_gp$passpercentage, def_gp[2], FUN=max)
gp_quality <- aggregate(gp$passpercentage, gp[2], FUN=max)
gp_improvement <- gp_quality$x - def_gp_quality$x
cat("%defects with improvement > 0:", length(which(gp_improvement>0.0))*100/length(gp_improvement),"\n")
cat("%defects with improvement = 0:", length(which(gp_improvement==0.0))*100/length(gp_improvement),"\n")
cat("%defects with improvement < 0:", length(which(gp_improvement<0.0))*100/length(gp_improvement),"\n")

cat("#patches with improvement < 0:", length(which(gp_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(gp_improvement==0.0)), "\n")
cat("total #patches:", length(gp_improvement), "\n")

cat("min quality improvement:", min(gp_improvement), "\n")
cat("mean quality improvement:", mean(gp_improvement), "\n")
cat("median quality improvement:", median(gp_improvement), "\n")
cat("max quality improvement:", max(gp_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_gp$defect)), "\n")

pdf("gp_quality_improvement_subset.pdf", width=12, height=6)
dtf <- data.frame(x = gp_quality$defect,y = gp_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(stat = "identity", fill = "black") + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 40)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=20))
dev.off()

cat("PAR\n")
def_par_quality <- aggregate(def_par$passpercentage, def_par[2], FUN=max)
par_quality <- aggregate(par$passpercentage, par[2], FUN=max)
par_improvement <- par_quality$x - def_par_quality$x
cat("min quality improvement:", min(par_improvement), "\n")
cat("mean quality improvement:", mean(par_improvement), "\n")
cat("median quality improvement:", median(par_improvement), "\n")
cat("max quality improvement:", max(par_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_par$defect)), "\n")
cat("%defects with improvement > 0:", length(which(par_improvement>0.0))*100/length(par_improvement),"\n")
cat("%defects with improvement = 0:", length(which(par_improvement==0.0))*100/length(par_improvement),"\n")
cat("%defects with improvement < 0:", length(which(par_improvement<0.0))*100/length(par_improvement),"\n")
cat("#patches with improvement < 0:", length(which(par_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(par_improvement==0.0)), "\n")
cat("total #patches:", length(par_improvement), "\n")
pdf("par_quality_improvement_subset.pdf", width=12, height=6)
dtf <- data.frame(x = par_quality$defect,y = par_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(stat = "identity", fill = "black") + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 40)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=20))
dev.off()

cat("TRP\n")
def_trp_quality <- aggregate(def_trp$passpercentage, def_trp[2], FUN=max)
trp_quality <- aggregate(trp$passpercentage, trp[2], FUN=max)
trp_improvement <- trp_quality$x - def_trp_quality$x
cat("min quality improvement:", min(trp_improvement), "\n")
cat("mean quality improvement:", mean(trp_improvement), "\n")
cat("median quality improvement:", median(trp_improvement), "\n")
cat("max quality improvement:", max(trp_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_trp$defect)), "\n")
cat("%defects with improvement > 0:", length(which(trp_improvement>0.0))*100/length(trp_improvement),"\n")
cat("%defects with improvement = 0:", length(which(trp_improvement==0.0))*100/length(trp_improvement),"\n")
cat("%defects with improvement < 0:", length(which(trp_improvement<0.0))*100/length(trp_improvement),"\n")
cat("#patches with improvement < 0:", length(which(trp_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(trp_improvement==0.0)), "\n")
cat("total #patches:", length(trp_improvement), "\n")
pdf("trp_quality_improvement_subset.pdf", width=12, height=6)
dtf <- data.frame(x = trp_quality$defect,y = trp_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(stat = "identity", fill = "black") + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 40)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=20))
dev.off()

cat("SimFix\n")
def_sim_quality <- aggregate(def_sim$passpercentage, def_sim[2], FUN=max)
sim_quality <- aggregate(sim$passpercentage, sim[2], FUN=max)
sim_improvement <- sim_quality$x - def_sim_quality$x
cat("min quality improvement:", min(sim_improvement), "\n")
cat("mean quality improvement:", mean(sim_improvement), "\n")
cat("median quality improvement:", median(sim_improvement), "\n")
cat("max quality improvement:", max(sim_improvement), "\n")
cat("number of defects evaluated:", length(unique(def_sim$defect)), "\n")
cat("%defects with improvement > 0:", length(which(sim_improvement>0.0))*100/length(sim_improvement),"\n")
cat("%defects with improvement = 0:", length(which(sim_improvement==0.0))*100/length(sim_improvement),"\n")
cat("%defects with improvement < 0:", length(which(sim_improvement<0.0))*100/length(sim_improvement),"\n")
cat("#patches with improvement < 0:", length(which(sim_improvement<0.0)), "\n")
cat("#patches with improvement = 0:", length(which(sim_improvement==0.0)), "\n")
cat("number of defects evaluated:", length(unique(def_sim$defect)), "\n")
cat("defects evaluated:", unique(def_sim$defect), "\n")
cat("total #patches:", length(sim_improvement), "\n")
pdf("sim_quality_improvement_subset.pdf", width=12, height=6)
dtf <- data.frame(x = sim_quality$defect,y = sim_improvement)
ggplot(dtf, aes(x, y)) + geom_bar(width=1, stat = "identity", fill = "black", position = position_dodge(width = 2)) + scale_y_continuous("patch quality improvement (%)", limits=c(-40, 40)) + geom_hline(yintercept=0) + xlab("defect") + theme(text = element_text(size=20)) + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, margin=margin(5,0,0,0))) 
dev.off()
