library(dplyr)
library(ggplot2)
library(ggpubr)
theme_set(theme_pubr())

eval_defects <- read.csv(file = "../evaluation-defects.txt")
gp_rq2_all<- read.csv(file="gp_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
trp_rq2_all <- read.csv(file="trp_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)
par_rq2_all <- read.csv(file="par_rq2_overall.csv", head=TRUE, sep=",", stringsAsFactors=FALSE)

## comment following block of code to consider all defects and remove _all from above 3 variables
evaldefectsgp <- intersect(gp_rq2_all$defect, eval_defects$defect)
evaldefectstrp <- intersect(trp_rq2_all$defect, eval_defects$defect)
evaldefectspar <- intersect(par_rq2_all$defect, eval_defects$defect)
gp_rq2 <- subset(gp_rq2_all, gp_rq2_all$defect%in%evaldefectsgp == TRUE)
trp_rq2 <- subset(trp_rq2_all, trp_rq2_all$defect%in%evaldefectstrp == TRUE)
par_rq2 <- subset(par_rq2_all, par_rq2_all$defect%in%evaldefectspar == TRUE)
###############################################################

cat("GenProg\n")
cat("min quality:", min(gp_rq2$passpercentage), "\n")
cat("mean quality:", mean(gp_rq2$passpercentage), "\n")
cat("median quality", median(gp_rq2$passpercentage), "\n")
cat("max quality:", max(gp_rq2$passpercentage), "\n")
cat("100% pass patches:", length(which(gp_rq2$passpercentage==100))/length(gp_rq2$passpercentage), "\n")
pdf("gp_patchquality_subset.pdf")
par(mgp=c(4.5,1.5,0))
par(mar=c(6,6.6,2,2))
h <- hist(gp_rq2$passpercentage, plot = FALSE) #, col="Black", xlab="patch quality (%)", ylab="patch count", main="GenProg", ylim=c(0,130), cex.lab=3, cex.axis=3, cex.main=3, cex.sub=3, xaxt="n", yaxt="n")
plot(h, col="Black", xlab="patch quality (%)", ylab="patch count", main="GenProg", ylim=c(0,130), cex.lab=3, cex.axis=3, cex.main=3, cex.sub=3, xaxt="n", yaxt="n")
axis(cex.axis=3,side=1,at=seq(60,100, by=10))
axis(cex.axis=3,side=2,at=seq(0,130, by=10))
text(h$mids, h$counts + 1, ifelse(h$counts == 0, "", h$counts), cex=2.5, pos=3)
dev.off()

cat("Par\n")
cat("min quality:", min(par_rq2$passpercentage), "\n")
cat("mean quality:", mean(par_rq2$passpercentage), "\n")
cat("median quality", median(par_rq2$passpercentage), "\n")
cat("max quality:", max(par_rq2$passpercentage), "\n")
cat("100% pass patches:", length(which(par_rq2$passpercentage==100))/length(par_rq2$passpercentage), "\n")
pdf("par_patchquality_subset.pdf")
par(mgp=c(4.5,1.5,0))
par(mar=c(6,6.6,2,2))
h <- hist(par_rq2$passpercentage, plot = FALSE)
plot(h, col="Black", xlab="patch quality (%)", ylab="patch count", main="Par", ylim=c(0,80), cex.lab=3, cex.axis=3, cex.main=3, cex.sub=3, xaxt="n", yaxt="n")
axis(cex.axis=3,side=1,at=seq(60,100, by=10))
axis(cex.axis=3,side=2,at=seq(0,80, by=20))
text(h$mids, h$counts + 1, ifelse(h$counts == 0, "", h$counts), cex=2.5, pos=3)
dev.off()

cat("TRPAutoRepair\n")
cat("min quality:", min(trp_rq2$passpercentage), "\n")
cat("mean quality:", mean(trp_rq2$passpercentage), "\n")
cat("median quality", median(trp_rq2$passpercentage), "\n")
cat("max quality:", max(trp_rq2$passpercentage), "\n")
cat("100% pass patches:", length(which(trp_rq2$passpercentage==100))/length(trp_rq2$passpercentage), "\n")
pdf("trp_patchquality_subset.pdf")
par(mgp=c(4.5,1.5,0))
par(mar=c(6,6.6,2,2))
h <- hist(trp_rq2$passpercentage, plot = FALSE)
plot(h, col="Black", xlab="patch quality (%)", ylab="patch count", main="TRPAutoRepair", ylim=c(0,130), cex.lab=3, cex.axis=3, cex.main=3, cex.sub=3, xaxt="n", yaxt="n")
axis(cex.axis=3,side=1,at=seq(60,100, by=10))
axis(cex.axis=3,side=2,at=seq(0,130, by=20))
text(h$mids, h$counts + 1, ifelse(h$counts == 0, "", h$counts), cex=2.5, pos=3)
dev.off()
